apiVersion: apps/v1
kind: Statefulset
metadata:
  creationTimestamp: null
  name: spreadss
spec:
  replicas: 3
  selector:
    matchLabels:
      pod: stretchedss
  template:
    metadata:
      name: mypod
      labels:
        pod: stretchedss
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            pod: stretchedss
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            pod: stretchedss
      containers:
      - name: pause
        image: registry.k8s.io/pause:3.1
