apiVersion: apps/v1
kind: Deployment
# systempool set with taint CriticalAddonsOnly=true:NoSchedule
#  systempool spans across all 3 zone
# three nodepools for workload aka work1 - all 3 set with taint work1only=yes:NoSchedule
#  z1 in zone1
#  z2 in zone2
#  z3 in zone3
# other nodepools with or without taint
#  all zone or specific zones
# with the following yaml, workload will land evenly in z1,z2,z3 and also evenly within z1,z2,z3
# k scale deploy spreaddeploy --replicas=12  (use multiples of total # of nodes in z1,z2,3)
# k get pod -o wide --sort-by=.spec.nodeName
metadata:
  creationTimestamp: null
  name: spreaddeploy
spec:
  replicas: 3
  selector:
    matchLabels:
      pod: stretched
  template:
    metadata:
      name: mypod
      labels:
        pod: stretched
    spec:
      affinity: 
        nodeAffinity: 
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.azure.com/agentpool
                operator: In
                values:
                - z1
                - z2
                - z3
      tolerations: 
      - key: "work1only"
        operator: "Equal"
        value: "yes"
        effect: "NoSchedule"
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            pod: stretched
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            pod: stretched
      containers:
      - name: pause
        image: registry.k8s.io/pause:3.1
